import com.binod.DrollsKnowledgeBase.User
import com.binod.DrollsKnowledgeBase.CompartimentType

rule "Buget too low for D Type Apartment"
	when 
		user: User( (_chosenCompartiment == CompartimentType.D) && (_maxBuget < _apartamentArea * _chosenCityZone.get_zoneMedianPricePerSquareMeters()))
	then
		System.out.println("Buget is too low for D Type Apartament in Selected Zone: "+ user.get_chosenCityZone().get_zoneName());
	end

rule "Buget too low for SD Type Apartment"
	when
		user: User( (_chosenCompartiment == CompartimentType.SD) && (_maxBuget < _apartamentArea * _chosenCityZone.get_zoneMedianPricePerSquareMeters()))
	then
		System.out.println("Buget is too low for D Type Apartament in Selected Zone: "+ user.get_chosenCityZone().get_zoneName());
	end

rule "Buget too low for ND Type Apartment"
	when
		user: User( (_chosenCompartiment == CompartimentType.ND) && (_maxBuget < _apartamentArea * _chosenCityZone.get_zoneMedianPricePerSquareMeters()))
	then
		System.out.println("Buget is too low for D Type Apartament in Selected Zone: "+ user.get_chosenCityZone().get_zoneName());
	end

rule "Buget too low for OP Type Apartment"
	when
		user: User( (_chosenCompartiment == CompartimentType.OP) && (_maxBuget < _apartamentArea * _chosenCityZone.get_zoneMedianPricePerSquareMeters()))
	then
		System.out.println("Buget is too low for D Type Apartament in Selected Zone: "+ user.get_chosenCityZone().get_zoneName());
	end

